In [2]:
import numpy as np

# Array type, 형태

In [3]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 :', array1.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 : (3,)


(3,) : 1차원 array로 3개의 데이터를 가지고 있다는 뜻  
 (1,3) == (3,)

In [5]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)


(2, 3) : 2차원 array, 2개의 row와 3개의 column으로 구성되어 2*3 6개의 데이터를 가지고 있음

In [6]:
array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 :', array3.shape)

array3 type :  <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


(1, 3) : 2차원 array, 1개의 row 3개의 column 3개의 데이터

## array의 차원 확인

In [7]:
print(f'array1 : {array1.ndim}차원 \narray2 : {array2.ndim}차원 \narray3 : {array3.ndim}차원')

array1 : 1차원 
array2 : 2차원 
array3 : 2차원


## ndarray dataType 확인

ndarray 내의 data type은 같은 type만 가능

In [8]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


만약 다른 타입이 들어있는 리스트를 ndarray로 변경하면 크기가 더 큰 타입으로 타입이 변환됨  
int < float < str

In [12]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2.0, 3.4]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.4] float64


## data Type 변경

In [13]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype('float64')
print(arr_float, arr_float.dtype)

[1. 2. 3.] float64


In [14]:
arr_int1= arr_float.astype('int32')
print(arr_int1, arr_int1.dtype)

[1 2 3] int32


In [17]:
arr_float1 = np.array([1.3, 2.5, 3.6])
arr_float1 = arr_float1.astype('int32') # 원본이 변경되지 않으므로 변수에 저장해야함
print(arr_float1, arr_float1.dtype)

[1 2 3] int32


## 간단하게 array생성

- arange() : range()와 같음
- zeros() : tuple형태 입력 -> 데이터를 0으로 채워 ndarray반환
- ones() : tuple 형태 입력 -> 데이터를 1로 채워 ndarray 반환

In [18]:
arr = np.arange(10)
print(arr)
print(arr.dtype, arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [19]:
arr_z = np.zeros((3, 2), dtype='int32') # datatype default : float64
print(arr_z)
print(arr_z.dtype, arr_z.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
arr_o = np.ones((2,3))
print(arr_o)
print(arr_o.dtype, arr_o.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
float64 (2, 3)


## array 차원과 크기 변경

데이터 갯수가 맞지 않으면 변경 불가

In [23]:
arr = np.arange(10)
print(f'arr : \n{arr}')

arr2 = arr.reshape(2, 5)
print(f'arr2 : \n{arr2}')

arr3 = arr.reshape(5, 2)
print(f'arr3 : \n{arr3}')

arr : 
[0 1 2 3 4 5 6 7 8 9]
arr2 : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


-1을 입력하면 나머지에 맞춰서 알아서 조정해줌  

In [25]:
arr = np.arange(10)
print(arr)

arr1 = arr.reshape(-1, 5)
print(arr1, arr1.shape)

arr2 = arr.reshape(5, -1)
print(arr2, arr2.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


reshape()은 (-1, 1)에 주로 사용됨  
어떤차원이든 2차원, 1개의 칼럼을 가진 ndarray로 변환

In [31]:
arr = np.arange(8)
arr3d = arr.reshape((2, 2, 2)) # 3차원
print(arr3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [32]:
print('arr3d : \n', arr3d.tolist()) # tolist() : array를 list로 변환

arr3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [36]:
arr= arr3d.reshape(-1, 1)
print('arr : \n', arr.tolist())
print('arr shape : \n', arr.shape)

arr : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr shape : 
 (8, 1)


## indexing

### 1차원 단일 값 추출, 수정

In [39]:
arr = np.arange(1, 10)
print('arr : ', arr)

val = arr[2]
print('val : ', val)

print(type(val))

arr :  [1 2 3 4 5 6 7 8 9]
val :  3
<class 'numpy.int32'>


In [40]:
arr[3] = 10
print(arr)

[ 1  2  3 10  5  6  7  8  9]


### 2차원 

In [47]:
arr = np.arange(1, 10)
arr2 = arr.reshape(3, 3)
print(arr2,'\n')

print('arr2[0, 0] :', arr2[0, 0])
print('arr2[1, 1] :', arr2[1, 1])
print('arr2[2, 0] :', arr2[2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

arr2[0, 0] : 1
arr2[1, 1] : 5
arr2[2, 0] : 7


In [43]:
arr2[0, 0] = 100
print(arr2)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


## 슬라이싱

### 1차원

In [45]:
arr = np.arange(1, 10)
print(arr)
print(arr[3:8])

[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]


### 2차원

In [55]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, '\n')

print(arr[0][2])
print(arr[:2, :1])
print(arr[1:3, :2])
print(arr[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

3
[[1]
 [4]]
[[4 5]
 [7 8]]
[1 2 3]


## 팬시 인덱싱

In [64]:
arr = np.arange(1,10).reshape(3, 3)
print(arr,'\n')

print(arr[[0,1], 2]) # (row),(col) -> (0,2),(1,2)
print(arr[[0, 2],[1, 2]]) # (0,1),(2,2)
print(arr[[0,1], :2]) # ((0,0),(0,1)),((1,0),(1,1)) -> (1, 2),(4, 5)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3 6]
[2 9]
[[1 2]
 [4 5]]


In [65]:
arr[[0,1],[2,2]]

array([3, 6])

In [66]:
arr[(0,1),(2,2)]

array([3, 6])

In [67]:
arr[0,1],[2,2]

(2, [2, 2])

In [81]:
arr[[0, 0, 2, 2], [1, 2, 0, 1]]

array([2, 3, 7, 8])

In [82]:
# arr[[[0, 0, 2, 2], [1, 2, 0, 1]]]

arr[[[0,1],[0,2],[2,0],[2,1]]]


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [7, 8, 9]],

       [[7, 8, 9],
        [1, 2, 3]],

       [[7, 8, 9],
        [4, 5, 6]]])

In [77]:
arr[[0,2],[1,0]]

array([2, 7])

## 불린 인덱싱

In [83]:
arr = np.arange(1, 10)

print(arr[arr > 5])

[6 7 8 9]


In [84]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [87]:
indexs = np.arange(5,9)

print(arr)
print(indexs)
print(arr[indexs]) # arr에서 index번호를 넣어서 호출한것과 같음 == arr[[5,6,7,8]]

[1 2 3 4 5 6 7 8 9]
[5 6 7 8]
[6 7 8 9]


## 행렬 정렬  

- srot()
- argsort()

In [93]:
arr = np.array([3, 1, 9, 5])
print(arr,'\n')

print(np.sort(arr)) # 원본을 유지하고 결과를 반환함
print(arr)

[3 1 9 5] 

[1 3 5 9]
[3 1 9 5]


In [94]:
print(arr.sort()) # 원본을 정렬시키고 결과를 반환하지 않음
print(arr)

None
[1 3 5 9]


In [95]:
arr[::-1] # 내림차순

array([9, 5, 3, 1])

### 2차원 행렬 정렬

In [3]:
arr = np.array([[8, 12], [7, 1]])

print(arr,'\n')
print(np.sort(arr, axis=0)) # 헷갈리니까 0 : ↓, 1:→ 으로 기억하기
print(np.sort(arr, axis=1)) 

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


## 정렬된 행렬의 인덱스 반환

In [4]:
arr = np.array([3, 1, 9, 5])

print(np.argsort(arr))

[1 0 3 2]


In [5]:
print(np.argsort(arr)[::-1]) #내림차순

[2 3 0 1]


In [6]:
arr_name = np.array(['suzan', 'suhee', 'minho', 'kate'])
arr_score = np.array([30, 50, 20, 100])

print(np.argsort(arr_score)) # 점수 정렬 인덱스 출력
print(arr_name[np.argsort(arr_score)]) # 점수정렬 인덱스로 이름 정렬

[2 0 1 3]
['minho' 'suzan' 'suhee' 'kate']


## 선형대수 연산

### 행렬 내적 (행렬 곱)

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9, 10], [11, 12]])

print(np.dot(a, b))

[[ 58  64]
 [139 154]]


In [8]:
print(np.dot(b, a))

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [9]:
c = np.array([[1,2,1],[2,4,1]])
d = np.array([[2,2,2],[2,1,4]])

print(np.dot(c, d)) # 곱하는행렬 갯수가 같아야함 c_row: 2개 d_col:3개 라서 연산 안됨

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

### 전치 행렬

In [11]:
a = np.array([[1,2], [3,4]])

print(a)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
